Image_Generation_Configs:
    - model_path: ./data/ddpm_dit_cifar_100_epochs.pth
      cfg: 3.0
      save_path: ./pretrained_class_conditional_inference_2_of_2_classes
      classes:
        - 3
        - 3
        - 4
        - 4
    - model_path: /data/patrick/10623-hw4/models/trained_qformer.pth
      cfg: 3.0
      save_path: ./silver_plane_cross_attention
      prompts:
        - "a photo of a silver plane in a green grassy background"
      gpt2_cache_dir: "./data"
      attn_save_dir: ./silver_plane_cross_attention_attn_maps # remove attn_save_dir and attn_timesteps if you don't want to capture and save the attention maps
      attn_timesteps:
        - 1000
        - 500
        - 100

    # =======================
    # 6.4: CFG sweeps for deer
    # =======================

    # w = 1.0
    - model_path: ./data/ddpm_dit_cifar_100_epochs.pth
      cfg: 1.0
      save_path: ./cfg_deer_w1.0
      classes:
        - 4

    # w = 2.0
    - model_path: ./data/ddpm_dit_cifar_100_epochs.pth
      cfg: 2.0
      save_path: ./cfg_deer_w2.0
      classes:
        - 4

    # w = 3.0
    - model_path: ./data/ddpm_dit_cifar_100_epochs.pth
      cfg: 3.0
      save_path: ./cfg_deer_w3.0
      classes:
        - 4

    # w = 4.0
    - model_path: ./data/ddpm_dit_cifar_100_epochs.pth
      cfg: 4.0
      save_path: ./cfg_deer_w4.0
      classes:
        - 4