Image_Generation_Configs:
  # ... your existing entries ...

  - model_path: /data/patrick/10623-hw4/models/trained_qformer.pth
    cfg: 3.0
    save_path: ./experiments/ood/ood_vehicle_grass
    num_query_tokens: 4
    transformer_hidden_size: 768
    n_T: 1000
    beta1: 1.0e-4
    beta2: 2.0e-2
    gpt2_layer_index: 12
    gpt2_cache_dir: ./data
    prompts:
      - "a photo of a vehicle that goes on grass"
      - "a photo of a vehicle that goes on grass"
      - "a photo of a vehicle that goes on grass"
      - "a photo of a vehicle that goes on grass"

  - model_path: /data/patrick/10623-hw4/models/trained_qformer.pth
    cfg: 3.0
    save_path: ./experiments/ood/ood_vehicle_water
    num_query_tokens: 4
    transformer_hidden_size: 768
    n_T: 1000
    beta1: 1.0e-4
    beta2: 2.0e-2
    gpt2_layer_index: 12
    gpt2_cache_dir: ./data
    prompts:
      - "a photo of a vehicle that goes in water"
      - "a photo of a vehicle that goes in water"
      - "a photo of a vehicle that goes in water"
      - "a photo of a vehicle that goes in water"
